# Generated by Django 3.2.7 on 2021-10-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_profile',
            new_name='user',
        ),
    ]
